name: Github Action Demo

on:
  push:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  demo:
    runs-on: ubuntu-latest
    env:
      ENV1: ${{ secrets.ENV1 }}
      ENV2: ${{ secrets.ENV2 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Go Run Main
        run: go run main.go
      - name: Git setting
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
      - name: Git Push
        run: |
          if (git diff --shortstat | grep '[0-9]'); then \
            git add *.csv; \
            git commit -m "update csv"; \
            git push origin HEAD:${GITHUB_REF}; \
          fi
